

<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="pt-BR"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="pt-BR"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="pt-BR"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="pt-BR"> <!--<![endif]-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="profile" href="https://gmpg.org/xfn/11" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<title>Dermacaps – Política de Privacidade</title>

</head>
<body class="page-template-default page page-id-2105 op-live-editor-page op-plugin has-header-image page-two-column colors-light">

<div class="container main-content">
<div id="content_area" class="">

<div class="row five-columns cf ui-sortable   " id="le_body_row_2" data-style=""><div class="fixed-width"><div class="one-fifth column cols narrow" id="le_body_row_2_col_1"></div><div class="three-fifths column cols" id="le_body_row_2_col_2"><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_1"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:31px;font-weight:bold;color:#004F2F;'>Política de Privacidade</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_2"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>Esta Política de Privacidade foi elaborada visando zelar pela confidencialidade, privacidade e proteção dos dados pessoais dos visitantes deste site e dos usuários de nossos serviços, protegendo essas informações de perdas, uso impróprio, acesso não autorizado, alteração e destruição.</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_3"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>1. Coleta e Uso das Informações</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_4"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>O acesso a este Site poderá ser condicionado ao cadastramento do visitante. Neste momento serão solicitadas informações capazes de identificá-lo, e será possível fazer o contato com nossos usuários. Ao decidir fornecer seus dados, o usuário declara conhecer e aceitar os termos desta Política. Por meio de cookies, o Site também recebe e armazena automaticamente informações sobre as atividades do navegador, incluindo endereço IP e a página acessada. Estes registros de atividades (logs) serão colocados apenas para fins estatísticos e de métricas dos serviços disponibilizados. O usuário tem ciência e concorda que as informações coletadas serão utilizadas para os seguintes propósitos: (a) informar a respeito de novos conteúdos, notícias e eventos; (b) atualização das informações de contato; (c) otimizar a usabilidade e a experiência interativa durante a navegação do usuário no Site; (d) elaborar estatísticas gerais, sem que haja identificação dos usuários; (e) responder às dúvidas e solicitações do próprio usuário; e (f) obedecer determinações legais e/ou judiciais. Também nos reservamos o direito de utilizar tais registros, de forma individualizada, em casos de investigação de ilícitos civis ou criminais, especialmente quando houver suspeita de fraude, ataques de hackers, alterações no sistema ou acesso indevido a informações protegidas e dados cadastrais de outros usuários.</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_5"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>1.1. Remarketing do Google</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_6"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>Nós utilizamos o recurso de Remarketing do Google Adwords para veicular anúncios em sites de parceiros do Google. Este recurso permite identificar que você visitou o nosso site e assim o Google pode exibir o nosso anúncio para você em diferentes websites. Diversos fornecedores de terceiros, inclusive o Google, compram espaços de publicidade em sites da Internet. Nós eventualmente contratamos o Google para exibir nossos anúncios nesses espaços. Para identificar a sua visita no nosso site, tanto outros fornecedores de terceiros, quanto o Google, utilizam-se de cookies. Você pode desativar o uso de cookies pelo Google acessando o Gerenciador de preferências de anúncio.</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_7"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>1.2. Remarketing do Facebook</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_8"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>Nós utilizamos o recurso de Remarketing do Facebook para veicular anúncios dentro do Facebook. Este recurso permite identificar que você visitou o nosso site e assim o Facebook pode exibir os nossos anúncios para você dentro do próprio Facebook. Para identificar a sua visita no nosso site utilizamos os cookies. Caso você venha a visualizar um dos nosso anúncios no Facebook e não queira mais visualizá-lo, no próprio anúncio existem opções para ocultar e não visualizar futuramente os nossos anúncios.</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_9"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>2. Guarda e Responsabilidade pelas Informações Coletadas</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_10"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>Qualquer informação fornecida pelos usuários será obtida e armazenada de acordo com os mais rígidos padrões de segurança e confiabilidade. Envidaremos nossos melhores esforços na manutenção da integridade das informações que nos forem fornecidas, razão pela qual não somos responsáveis pelos danos decorrentes do seu acesso e/ou utilização por terceiros estranhos. O acesso às informações coletadas é restrito aos colaboradores e pessoas autorizadas. Aqueles que utilizarem indevidamente essas informações, em violação desta Política de Privacidade, estarão sujeitos à sanções administrativas e disciplinares, sem exclusão das medidas legais cabíveis. A não ser por determinação legal ou judicial, as informações dos usuários cadastrados neste Site jamais serão transferidas a terceiros ou usadas para finalidades diferentes daquelas para as quais foram coletadas. Todos os dados pessoais coletados serão incorporados ao banco de dados deste Site, sendo seu responsável a 2B EMPREENDIMENTOS DIGITAIS LTDA - ME. (CNPJ: 21.302.413/0001-09)</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_11"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>2.1. Marketing</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_12"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>Não vendemos nem alugamos suas informações pessoais para terceiros para fins de marketing sem seu consentimento explícito. Podemos combinar suas informações com as informações que coletamos de outras empresas e usá-las para melhorar e personalizar nossos serviços, conteúdo e publicidade. Se não desejar receber nossas mensagens de marketing nem participar de nossos programas de personalização de anúncios, basta indicar sua preferência mandando-nos um e-mail para contato@dermacaps.com.br.</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_13"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>3. Informações, Opiniões e Conteúdos gerados por Terceiros</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_14"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>Este Site possibilita a participação de visitantes/usuários através de comentários, troca de informações, publicação de conteúdos gerados por terceiros e divulgação de anúncios publicitários. Os visitantes, usuários e anunciantes ficam desde já cientes de que não devem publicar informações, opiniões ou conteúdos imorais, ilegais, racistas, difamatórios, injuriosos, pornográficos, criminosos, ou qualquer conteúdo que viole os direitos do autor. Ficam cientes ainda que as informações, conteúdos ou opiniões fornecidos ou publicados livremente neste Site - à exceção das informações pessoais solicitadas para fins de cadastro - NÃO SERÃO SIGILOSAS NEM ESTÃO PROTEGIDAS POR ESTA POLÍTICA DE PRIVACIDADE, podendo ser livremente acessadas e visualizadas por outros visitantes e usuários. Ficam também vedados anúncios publicitários ou qualquer divulgação sobre produtos, serviços e/ou eventos que desrespeitem a lei, a moral e os bons costumes. Os responsáveis por este Site não se responsabilizam pelas informações, opiniões e conteúdos gerados por terceiros, e tampouco pela qualidade ou veracidade dos produtos, serviços ou eventos divulgados através do Site. Qualquer manifestação, reprodução, publicação imoral ou ilegal deverá ser notificada aos organizadores deste Site para que seja removida imediatamente. A notificação deverá ser encaminhada para o endereço dos responsáveis pelo Site (tópico anterior) ou para o seguinte endereço eletrônico: contato@dermacaps.com.br</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_15"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='font-size:26px;color:#004F2F;'>4. Responsabilidade dos Usuários</p>
</div> </div></div><div class="element-container cf" data-style="" id="le_body_row_2_col_2_el_16"><div class="element"> <div class="op-text-block" style="width:100%;text-align: left;"><p style='color:#004F2F;'>É de total responsabilidade do usuário a guarda de sua senha e de seu login de acesso, sendo que o mesmo é intransferivel para terceiros, pois poderá ocorrer o bloqueio do acesso caso o sistema reconheça acessos de diferentes IP's . Não é recomendada a utilização de senhas óbvias como datas especiais, nomes ou sequências numéricas. Caso o usuário tome conhecimento ou apenas suspeite que sua senha veio a ser descoberta, ele deverá alterá-la em sua página de cadastro. Nós temos o compromisso de proteger a privacidade on-line de crianças. Eventuais cadastros de menores ocorrerão apenas para fins de participação em áreas restritas do site com conteúdos educacionais. Os dados dos menores só serão utilizados para resposta a consultas, dúvidas acadêmicas, agendamento de palestras em escolas ou por motivo de estatísticas gerais. Recomendamos ainda que o menor esteja sempre sob a orientação e supervisão de seus responsáveis, que poderão, a qualquer momento, solicitar o cancelamento do cadastro. Esta Política está sujeita a constantes melhorias e aprimoramentos. Desse modo, recomendamos sua periódica consulta.</p>
</div> </div></div></div></div></div></div> </div>

</body>
</html>